@node 4.4.4.8, Chapter 5, 4.3, 4.4.4
@subsubsection Frames and Bindings

Frames are represented as lists of bindings, which are variable-value pairs:

@lisp
(define (make-binding variable value)
  (cons variable value))

(define (binding-variable binding)
  (car binding))

(define (binding-value binding)
  (cdr binding))

(define (binding-in-frame variable frame)
  (assoc variable frame))

(define (extend variable value frame)
  (cons (make-binding variable value) frame))
@end lisp

@quotation
@strong{@anchor{Exercise 4.71}Exercise 4.71:} Louis Reasoner wonders why the
@code{simple-query} and @code{disjoin} procedures (@ref{4.4.4.2}) are
implemented using explicit @code{delay} operations, rather than being defined
as follows:

@lisp
(define (simple-query 
         query-pattern frame-stream)
  (stream-flatmap
   (lambda (frame)
     (stream-append
      (find-assertions query-pattern frame)
      (apply-rules query-pattern frame)))
   frame-stream))

(define (disjoin disjuncts frame-stream)
  (if (empty-disjunction? disjuncts)
      the-empty-stream
      (interleave
       (qeval (first-disjunct disjuncts)
              frame-stream)
       (disjoin (rest-disjuncts disjuncts)
                frame-stream))))
@end lisp

Can you give examples of queries where these simpler definitions would lead to
undesirable behavior?
@end quotation

@quotation
@strong{@anchor{Exercise 4.72}Exercise 4.72:} Why do @code{disjoin} and
@code{stream-flatmap} interleave the streams rather than simply append them?
Give examples that illustrate why interleaving works better.  (Hint: Why did we
use @code{interleave} in @ref{3.5.3}?)
@end quotation

@quotation
@strong{@anchor{Exercise 4.73}Exercise 4.73:} Why does @code{flatten-stream}
use @code{delay} explicitly?  What would be wrong with defining it as follows:

@lisp
(define (flatten-stream stream)
  (if (stream-null? stream)
      the-empty-stream
      (interleave (stream-car stream)
                  (flatten-stream 
                   (stream-cdr stream)))))
@end lisp
@end quotation

@quotation
@strong{@anchor{Exercise 4.74}Exercise 4.74:} Alyssa P. Hacker proposes to use
a simpler version of @code{stream-flatmap} in @code{negate}, @code{lisp-value},
and @code{find-assertions}.  She observes that the procedure that is mapped
over the frame stream in these cases always produces either the empty stream or
a singleton stream, so no interleaving is needed when combining these streams.

@enumerate a

@item
Fill in the missing expressions in Alyssa's program.

@lisp
(define (simple-stream-flatmap proc s)
  (simple-flatten (stream-map proc s)))

(define (simple-flatten stream)
  (stream-map ⟨??⟩
              (stream-filter ⟨??⟩ 
                             stream)))
@end lisp

@item
Does the query system's behavior change if we change it in this way?

@end enumerate
@end quotation

@quotation
@strong{@anchor{Exercise 4.75}Exercise 4.75:} Implement for the query language
a new special form called @code{unique}.  @code{Unique} should succeed if there
is precisely one item in the data base satisfying a specified query.  For
example,

@lisp
(unique (job ?x (computer wizard)))
@end lisp

@noindent
should print the one-item stream

@lisp
(unique (job (Bitdiddle Ben)
             (computer wizard)))
@end lisp

@noindent
since Ben is the only computer wizard, and

@lisp
(unique (job ?x (computer programmer)))
@end lisp

@noindent
should print the empty stream, since there is more than one computer
programmer.  Moreover,

@lisp
(and (job ?x ?j) 
     (unique (job ?anyone ?j)))
@end lisp

@noindent
should list all the jobs that are filled by only one person, and the people who
fill them.

There are two parts to implementing @code{unique}.  The first is to write a
procedure that handles this special form, and the second is to make
@code{qeval} dispatch to that procedure.  The second part is trivial, since
@code{qeval} does its dispatching in a data-directed way.  If your procedure is
called @code{uniquely-asserted}, all you need to do is

@lisp
(put 'unique 'qeval uniquely-asserted)
@end lisp

@noindent
and @code{qeval} will dispatch to this procedure for every query whose
@code{type} (@code{car}) is the symbol @code{unique}.

The real problem is to write the procedure @code{uniquely-asserted}.  This
should take as input the @code{contents} (@code{cdr}) of the @code{unique}
query, together with a stream of frames.  For each frame in the stream, it
should use @code{qeval} to find the stream of all extensions to the frame that
satisfy the given query.  Any stream that does not have exactly one item in it
should be eliminated.  The remaining streams should be passed back to be
accumulated into one big stream that is the result of the @code{unique} query.
This is similar to the implementation of the @code{not} special form.

Test your implementation by forming a query that lists all people who supervise
precisely one person.
@end quotation

@quotation
@strong{@anchor{Exercise 4.76}Exercise 4.76:} Our implementation of @code{and}
as a series combination of queries (@ref{Figure 4.5}) is elegant, but it is
inefficient because in processing the second query of the @code{and} we must
scan the data base for each frame produced by the first query.  If the data
base has @math{n} elements, and a typical query produces a number of output frames
proportional to @math{n} (say @math{{n \,/\, k}}), then scanning the data base for each
frame produced by the first query will require @math{{n^2 /\, k}} calls to the
pattern matcher.  Another approach would be to process the two clauses of the
@code{and} separately, then look for all pairs of output frames that are
compatible.  If each query produces @math{{n \,/\, k}} output frames, then this means
that we must perform @math{{n^2 /\, k^2}} compatibility checks---a factor of @math{k}
fewer than the number of matches required in our current method.

Devise an implementation of @code{and} that uses this strategy.  You must
implement a procedure that takes two frames as inputs, checks whether the
bindings in the frames are compatible, and, if so, produces a frame that merges
the two sets of bindings.  This operation is similar to unification.
@end quotation

@quotation
@strong{@anchor{Exercise 4.77}Exercise 4.77:} In @ref{4.4.3} we saw
that @code{not} and @code{lisp-value} can cause the query language to give
``wrong'' answers if these filtering operations are applied to frames in which
variables are unbound.  Devise a way to fix this shortcoming.  One idea is to
perform the filtering in a ``delayed'' manner by appending to the frame a
``promise'' to filter that is fulfilled only when enough variables have been
bound to make the operation possible.  We could wait to perform filtering until
all other operations have been performed.  However, for efficiency's sake, we
would like to perform filtering as soon as possible so as to cut down on the
number of intermediate frames generated.
@end quotation

@quotation
@strong{@anchor{Exercise 4.78}Exercise 4.78:} Redesign the query language as a
nondeterministic program to be implemented using the evaluator of 
@ref{4.3}, rather than as a stream process.  In this approach, each query will
produce a single answer (rather than the stream of all answers) and the user
can type @code{try-again} to see more answers.  You should find that much of
the mechanism we built in this section is subsumed by nondeterministic search
and backtracking.  You will probably also find, however, that your new query
language has subtle differences in behavior from the one implemented here.  Can
you find examples that illustrate this difference?
@end quotation

@quotation
@strong{@anchor{Exercise 4.79}Exercise 4.79:} When we implemented the Lisp
evaluator in @ref{4.1}, we saw how to use local environments to avoid
name conflicts between the parameters of procedures.  For example, in
evaluating

@lisp
(define (square x) 
  (* x x))

(define (sum-of-squares x y)
  (+ (square x) (square y)))

(sum-of-squares 3 4)
@end lisp

@noindent
there is no confusion between the @code{x} in @code{square} and the @code{x} in
@code{sum-of-squares}, because we evaluate the body of each procedure in an
environment that is specially constructed to contain bindings for the local
variables.  In the query system, we used a different strategy to avoid name
conflicts in applying rules.  Each time we apply a rule we rename the variables
with new names that are guaranteed to be unique.  The analogous strategy for
the Lisp evaluator would be to do away with local environments and simply
rename the variables in the body of a procedure each time we apply the
procedure.

Implement for the query language a rule-application method that uses
environments rather than renaming.  See if you can build on your environment
structure to create constructs in the query language for dealing with large
systems, such as the rule analog of block-structured procedures.  Can you
relate any of this to the problem of making deductions in a context (e.g., ``If
I supposed that @math{P} were true, then I would be able to deduce @math{A} and
@math{B}.'') as a method of problem solving?  (This problem is open-ended.  A good
answer is probably worth a Ph.D.)
@end quotation

